# Generated by Django 2.2.12 on 2021-08-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0002_players_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='players_id',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='team_id',
        ),
        migrations.AddField(
            model_name='players',
            name='club',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='players',
            name='nation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teams',
            name='items',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='page',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='total_items',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='total_pages',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
